pipeline {
    agent any
    stages {
        stage('ansible') {
            agent { dockerfile { filename 'Dockerfile.ansible' } }   
            steps {
                sh 'ansible-playbook --version'
            }
        }
        stage('bicep') {
            agent { dockerfile { filename 'Dockerfile.bicep' } }   
            steps {
                sh 'bicep --help'
            }
        }
        stage('node') {
            agent { dockerfile { filename 'Dockerfile.node' } }   
            steps {
                sh 'node --version'
            }
        }
        stage('powershellcore') {
            agent { dockerfile { filename 'Dockerfile.powershellcore' } }   
            steps {
                sh '$PSVersionTable'
            }
        }
        stage('python') {
            agent { dockerfile { filename 'Dockerfile.python' } }   
            steps {
                sh 'python --version'
            }
        }
        stage('terraform') {
            agent { dockerfile { filename 'Dockerfile.terraform' } }   
            steps {
                sh 'tf'
            }
        }
    }
}
